#
# License-Identifier: GPL
#
# Copyright (C) 2025 The Yambo Team
#
# Authors (see AUTHORS file for details): AM MN
#
ifeq ($(wildcard compile/global/defs.mk),compile/global/defs.mk)
  include compile/defs.mk
endif
#
# Library link order is INTRINSIC to LetzElPhC's dependency.
# Static linker is left-to-right: symbol-users before symbol-providers.
#
# Dependency tiers (each tier depends only on equal/lower tiers):
#   T5 drivers      : interpolation, elph
#   T4 QE I/O       : io/qe
#   T3 main I/O     : io
#   T2 kernels+pp   : dvloc, symmetries, nonloc, preprocessor
#   T1 primitives   : fft, parser, phonon, wfc
#   T0 base+vendors : common, common/kdtree, io/ezxml, common/ELPH_hash_map,
#                     parser/inih, common/cwalk
#
# elph (T5) hosts the Fortran-to-C ABI boundary (ep_f2c_bridge.c):
#   elph_driver_f2c / elph_driver_cb_f2c / elph_driver_cb2_f2c
# These are the ONLY entry points yambo_ep calls into LetzElPhC.
#
# Order generated by check_dep.py topological sort (most-dependent first).
#
EP_S1= [Sletz,interpolation] 
EP_S2= [Sletz,io/qe] [Sletz,common/ELPH_hash_map] [Sletz,common] [Sletz,symmetries] [Sletz,nonloc] 
EP_S3= [Sletz,dvloc] [Sletz,io] [Sletz,io/ezxml]
EP_S4= [Sletz,wfc] [Sletz,fft] [Sletz,dvloc] [Sletz,common/cwalk] [Sletz,preprocessor]
EP_S5= [Sletz,phonon]  [Sletz,parser/inih] [Sletz,parser]
EP_S6= [Sletz,common/kdtree] [Sletz,elph]
#
ifneq (,$(filter yambo_ep ypp_ep,$(MAKECMDGOALS)))
  SERVICES_LIBS += ${EP_S1} ${EP_S2} ${EP_S3} ${EP_S4} ${EP_S5} ${EP_S6}
endif
